apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tenkacloud
type: Opaque
stringData:
  username: postgres
  password: postgres
  database: tenkacloud
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: tenkacloud
type: Opaque
stringData:
  # openssl rand -base64 32 で生成した値
  secret: "k8s-local-dev-secret-key-32-bytes-long"
