apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app
  namespace: tenkacloud
  labels:
    app: admin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
        - name: admin-app
          image: tenkacloud/admin-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: AUTH_SECRET
              value: "secret"
            - name: AUTH_URL
              value: "http://localhost:3001"
            - name: AUTH_KEYCLOAK_ID
              value: "admin-app"
            - name: AUTH_KEYCLOAK_SECRET
              value: "secret"
            - name: AUTH_KEYCLOAK_ISSUER
              value: "http://keycloak:8080/realms/tenkacloud"
            - name: NEXTAUTH_URL
              value: "http://localhost:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-app
  namespace: tenkacloud
spec:
  selector:
    app: admin-app
  ports:
    - port: 3001
      targetPort: 3001
