apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-site
  namespace: tenkacloud
  labels:
    app: landing-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-site
  template:
    metadata:
      labels:
        app: landing-site
    spec:
      containers:
        - name: landing-site
          image: tenkacloud/landing-site:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: landing-site
  namespace: tenkacloud
spec:
  selector:
    app: landing-site
  ports:
    - port: 3003
      targetPort: 3003
