apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-app
  namespace: tenkacloud
  labels:
    app: participant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-app
  template:
    metadata:
      labels:
        app: participant-app
    spec:
      containers:
        - name: participant-app
          image: tenkacloud/participant-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: AUTH_SECRET
              value: "secret"
            - name: AUTH_URL
              value: "http://localhost:3002"
            - name: AUTH_KEYCLOAK_ID
              value: "participant-app"
            - name: AUTH_KEYCLOAK_SECRET
              value: "secret"
            - name: AUTH_KEYCLOAK_ISSUER
              value: "http://keycloak:8080/realms/tenkacloud"
            - name: NEXTAUTH_URL
              value: "http://localhost:3002"
---
apiVersion: v1
kind: Service
metadata:
  name: participant-app
  namespace: tenkacloud
spec:
  selector:
    app: participant-app
  ports:
    - port: 3002
      targetPort: 3002
